name: Deploy to https://rich.blog

on:
    # Triggers the workflow only for the main branch
    push:
        branches: [main]
        paths-ignore:
            - '.github/**'
            - '.editorconfig'
            - '.gitattributes'
            - '.gitignore'
            - '.editorconfig'
            - 'package.json'
            - 'README.md'
            - 'LICENSE'
            - '.wp-env.js'

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get latest code
              uses: actions/checkout@v2

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@2.0.0
              env:
                  FTP_SERVER: ${{ secrets.FTP_SERVER }}
                  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
                  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
                  REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
                  METHOD: sftp
                  PORT: 22
                  ARGS: --exclude=README.md --exclude-glob=.git*/** --exclude-glob=.git** --exclude-glob=node_modules/** --exclude=package.json --exclude=composer.json --exclude=package-lock.json --exclude=.wp-env.json --exclude=.wp-env-generator.json
